- name: Add MongoDB to apt keys
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10

- name: Add MongoDB repository to apt
  apt_repository: repo="deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" state=present

- name: Install MongoDB
  apt: name=mongodb-10gen update_cache=yes state=latest
