- hosts: wakeupheroku
  user: app
  sudo: yes
  gather_facts: no
  vars:
    - app_name: wakeup_heroku
    - app_dir: /home/app/wakeup_heroku
    - os_version: ubuntu-12-04
    - ruby_version: 2.1.2
    - run_bootstrap: n
    - stage: production
  roles:
    - { role: bootstrap, when: run_bootstrap == 'y' }
    - { role: common, tags: [common] }
    - { role: nginx, tags: [nginx] }
    - { role: mongodb, tags: [mongodb] }
    - { role: backup, tags: [backup], backup_type: mongodb, backup_database_name: wakeup_heroku }
    - { role: rails, tags: [rails] }
    - { role: logrotate, tags: [logrotate] }
    - { role: unicorn, tags: [unicorn] }
